-- RTFCLMGZN - billing: the three user columns (migration 002)
--
--   *** DO NOT RUN THIS FILE WITH --file. RUN EACH LINE WITH --command. ***
--
-- SQLite has no "ADD COLUMN IF NOT EXISTS". D1 aborts an entire .sql file on the
-- first error AND ROLLS THE WHOLE THING BACK. users.stripe_customer_id already
-- existed in the original auth schema, so line 3 below always failed, which rolled
-- back lines 1 and 2 -- meaning plan_source and plan_expires_at could NEVER be
-- added, no matter how many times the migration was run. The failure was silent:
-- voucher redemption burned the code, then could not write the plan, and the
-- account stayed on 'free'. That cost an evening. Run them separately:
--
--   wrangler d1 execute rtfclmgzn --remote --command "ALTER TABLE users ADD COLUMN plan_source TEXT"
--   wrangler d1 execute rtfclmgzn --remote --command "ALTER TABLE users ADD COLUMN plan_expires_at TEXT"
--   wrangler d1 execute rtfclmgzn --remote --command "ALTER TABLE users ADD COLUMN stripe_customer_id TEXT"
--
-- A "duplicate column name" from any one of those is fine and means that column is
-- already there. Because each runs on its own, one failing no longer harms the rest.
-- SETUP_BILLING.bat does exactly this. Check the result with:
--
--   wrangler d1 execute rtfclmgzn --remote --command "PRAGMA table_info(users)"
--
-- The tables (subscriptions, vouchers, voucher_redemptions, stripe_events) live in
-- db/002b_billing_tables.sql, which is all CREATE ... IF NOT EXISTS and therefore
-- safe to run as a file, any number of times.
--
--  plan            already exists: 'free' | 'plus'
--  plan_source     'stripe' | 'voucher' | 'comp'   (NULL while free)
--  plan_expires_at NULL means no expiry. A timestamp means it lapses then, which is
--                  how voucher trials end without a scheduled job: getSessionUser()
--                  compares it on every request and stops returning 'plus'.
