-- RTFCLMGZN — starter voucher codes.
-- Applied by SETUP_BILLING.bat. Safe to re-run: INSERT OR IGNORE skips existing codes.
-- Retire a whole batch later with:  UPDATE vouchers SET active=0 WHERE batch='gift-3mo';

INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-FOUNDER', 'lifetime', NULL, NULL, 1, NULL, 'Nafiul — owner account', 'owner');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-5BH7-ANRC-MW7C', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-VG3M-N55U-VBEJ', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-RTMT-CAZU-6XM2', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-KSQK-QZZX-HK4T', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-KY5G-GRCB-3DK4', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-EMU9-B7PT-HC8E', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-BVCB-5JQ3-SWX5', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-GKBZ-SMSD-22BV', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-MHAD-43JU-MY34', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-Y5Y8-M5HV-62DN', 'lifetime', NULL, NULL, 1, NULL, 'friends & family', 'gift-lifetime');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-NVYG-UPKW-B5ZC', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-BQ8N-WRVT-NWH9', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-YAJD-858Z-GFP3', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-8WYA-Y7VB-5E47', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-JS85-ZAPE-H5VG', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-YTJB-4KCE-GSDA', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-UHS8-WVE3-EDVQ', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-B2MT-J32H-SWPQ', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-CT4Q-J5MF-PW7Z', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-74BN-CK54-FB4T', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-QFGW-KRCW-QZD5', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-PB7H-RDG5-G937', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-24E9-4BTN-2CHK', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-6XN9-JYGS-37GM', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-XT6M-4MX8-HSA9', 'free_days', 365, NULL, 1, NULL, '12 months free', 'gift-12mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-GDTX-NVF6-6RJC', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-E5FW-Y8U9-2VN4', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-VR73-XKZM-84KZ', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-QFYR-TDFX-WJUC', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-473D-UBWZ-QDDF', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-JH39-9FQS-UGGK', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-5EVT-YBPS-9PK2', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-AWE4-23PQ-9E7X', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-PT96-FK6A-8JGR', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-97ZC-SDR2-S3HF', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-UYVU-8EVC-7HST', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-X5Z9-7E8K-XP9C', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-AP5R-5V4G-GPPK', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-NCDN-FCCP-4MKK', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-77WA-QAXS-ZWE5', 'free_days', 180, NULL, 1, NULL, '6 months free', 'gift-6mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-YSP8-AY9U-YFBM', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-7XWG-JPCH-WRUS', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-5G42-UVGA-9T8S', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-FETP-MYPE-YQ44', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-KXY4-PJV4-JJFD', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-AJDS-V9PZ-8B52', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-7VXC-VB92-W7AV', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-E4KC-A9ZU-2QY9', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-GDQP-PTBZ-8BMB', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-W7GM-JPDQ-5PZZ', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-TF88-HA75-4X48', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-67VW-5XAN-JR6E', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-362J-5M3A-MR9Z', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-VSMM-FM4E-KX25', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-87BG-ZVRR-XK2U', 'free_days', 90, NULL, 1, NULL, '3 months free', 'gift-3mo');
INSERT OR IGNORE INTO vouchers (code, kind, value, stripe_coupon_id, max_redemptions, expires_at, note, batch) VALUES ('RTFC-LAUNCH90', 'free_days', 90, NULL, NULL, NULL, 'public launch promo — unlimited uses', 'launch');
