-- REMOVED FROM THE REPOSITORY 2026-09-20.
--
-- This file held the INSERT statements for 57 live gift codes, including 11
-- lifetime Plus grants, in a PUBLIC repository. Anyone who read it could grant
-- themselves permanent paid access.
--
-- The real file now lives at agents/billing/private/starter_vouchers.sql,
-- which .gitignore keeps out of git.
--
-- git history still contains the old codes, so deleting this file does not
-- revoke them. Retire the exposed batches in the D1 console:
--
--   UPDATE vouchers SET active=0
--    WHERE batch IN ('gift-lifetime','gift-12mo','gift-6mo','gift-3mo','owner','launch','short');
--
-- then mint replacements with agents/billing/mint_vouchers.py.
